---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fullname" . }}-burrow"
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
{{ toYaml .Values.config | indent 2 }}
