{{if .Values.datadog.enabled}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-dd-conf
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  burrow.yaml: |
    init_config:
    instances:
    - burrow_uri: http://localhost:{{.Values.service.internalPort}}
      clusters:
{{toYaml .Values.datadog.checks_d.clusters | indent 8}}
{{if .Values.datadog.checks_d.tags}}
      tags:
{{toYaml .Values.datadog.checks_d.tags | indent 8}}
{{end}}
{{end}}
