apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  datadog.api.key: {{ .Values.datadog.ApiKey | b64enc }}
